AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless Application Model for FDIO-Lambda
Resources:
  fdio:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: bin/
      Handler: fdio-lambda
      Runtime: go1.x
      Tracing: Active
      Timeout: 180
      Policies:
        - AmazonS3FullAccess
        - AmazonSSMReadOnlyAccess
      Environment:
        Variables:
          region: us-west-2
          s3bucket: retgits-fdio
      Tags:
        version: "0.0.10"
      Events:
        fdio:
          Type: Schedule
          Properties:
            Schedule: cron(0 1 * * ? *) # Run at 1:00 am (UTC) every day
      Description: Collecting stats on Flogo
      MemorySize: 128